use super::*;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdminLiveIngestCreatorOverview {
    pub creator_id: Id,
    pub handle: String,
    pub display_name: String,
    pub active_sessions: i64,
    pub stale_sessions: i64,
    pub terminal_sessions: i64,
    pub ready_outputs: i64,
    pub degraded_outputs: i64,
    pub failed_outputs: i64,
    pub archive_finalizing_outputs: i64,
    pub archive_complete_outputs: i64,
    pub artifact_attention_outputs: i64,
    pub manifest_path_missing_outputs: i64,
    pub archive_path_missing_outputs: i64,
    pub last_runtime_state: Option<String>,
    pub last_packaging_status: Option<String>,
    pub last_archive_status: Option<String>,
    pub last_manifest_artifact_state: Option<String>,
    pub last_archive_artifact_state: Option<String>,
    pub avg_ready_latency_seconds: Option<f64>,
    pub avg_archive_completion_seconds: Option<f64>,
    pub total_samples: i64,
    pub degraded_samples: i64,
    pub failure_samples: i64,
    pub advisory_critical_samples: i64,
    pub advisory_repairable_samples: i64,
    pub runtime_artifact_reconciliation_samples: i64,
    pub runtime_archive_completion_samples: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdminLiveIngestOverview {
    pub active_sessions: i64,
    pub stale_sessions: i64,
    pub terminal_sessions: i64,
    pub unique_creators: i64,
    pub ready_outputs: i64,
    pub degraded_outputs: i64,
    pub failed_outputs: i64,
    pub archive_finalizing_outputs: i64,
    pub archive_complete_outputs: i64,
    pub artifact_attention_outputs: i64,
    pub manifest_path_missing_outputs: i64,
    pub archive_path_missing_outputs: i64,
    pub avg_ready_latency_seconds: Option<f64>,
    pub avg_archive_completion_seconds: Option<f64>,
    pub total_samples: i64,
    pub degraded_samples: i64,
    pub failure_samples: i64,
    pub advisory_critical_samples: i64,
    pub advisory_repairable_samples: i64,
    pub runtime_artifact_reconciliation_samples: i64,
    pub runtime_archive_completion_samples: i64,
    pub peak_host_channel_count: i64,
    pub peak_mirror_channel_count: i64,
    pub peak_shared_program_mirror_channel_count: i64,
    pub peak_guest_isolated_mirror_channel_count: i64,
    pub peak_archive_target_count: i64,
    pub peak_active_target_count: i64,
    pub peak_degraded_target_count: i64,
    pub peak_armed_target_count: i64,
    pub peak_pending_source_target_count: i64,
    pub last_host_channel_count: Option<i64>,
    pub last_mirror_channel_count: Option<i64>,
    pub last_shared_program_mirror_channel_count: Option<i64>,
    pub last_guest_isolated_mirror_channel_count: Option<i64>,
    pub last_archive_target_count: Option<i64>,
    pub last_active_target_count: Option<i64>,
    pub last_degraded_target_count: Option<i64>,
    pub last_armed_target_count: Option<i64>,
    pub last_pending_source_target_count: Option<i64>,
    pub creator_breakdown: Vec<AdminLiveIngestCreatorOverview>,
}
