use super::*;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LiveIngestEvent {
    pub id: Id,
    pub session_id: Id,
    pub creator_id: Id,
    pub broadcast_id: Id,
    pub event_type: String,
    pub payload: Value,
    pub created_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LiveRuntimeOutput {
    pub id: Id,
    pub session_id: Id,
    pub creator_id: Id,
    pub broadcast_id: Id,
    pub runtime_state: String,
    pub packaging_status: String,
    pub archive_status: String,
    pub runtime_class: String,
    pub latency_profile: String,
    pub segment_format: String,
    pub partial_segments_enabled: bool,
    pub blocking_reload_enabled: bool,
    pub target_segment_duration_sec: i64,
    pub hold_back_segments: i64,
    pub discontinuity_sequence: i64,
    pub ladder_policy: String,
    pub content_class: String,
    pub manifest_relative_path: Option<String>,
    pub archive_relative_path: Option<String>,
    pub last_error: Option<String>,
    pub last_runtime_event_at: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LiveRuntimeTarget {
    pub id: Id,
    pub session_id: Id,
    pub creator_id: Id,
    pub broadcast_id: Id,
    pub target_kind: String,
    pub target_key: String,
    pub target_label: String,
    pub route_state: String,
    pub target_creator_id: Option<Id>,
    pub target_broadcast_id: Option<Id>,
    pub playback_enabled: bool,
    pub recording_enabled: bool,
    pub mix_minus_required: bool,
    pub relative_path: Option<String>,
    pub source_participant_ids: Vec<Id>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LiveRuntimeTelemetry {
    pub id: Id,
    pub session_id: Id,
    pub creator_id: Id,
    pub broadcast_id: Id,
    pub sample_kind: String,
    pub runtime_state: String,
    pub packaging_status: String,
    pub archive_status: String,
    pub bitrate_kbps: i64,
    pub viewers: i64,
    pub dropped_frames: i64,
    pub cpu_percent: Option<i64>,
    pub free_disk_gb: Option<f64>,
    pub detail: Value,
    pub collected_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LiveRuntimeTelemetrySummary {
    pub total_samples: i64,
    pub degraded_samples: i64,
    pub packaging_degraded_samples: i64,
    pub failure_samples: i64,
    pub archive_failure_samples: i64,
    pub reconnect_events: i64,
    pub probe_samples: i64,
    pub validation_issue_samples: i64,
    pub repairable_validation_samples: i64,
    pub advisory_critical_samples: i64,
    pub advisory_repairable_samples: i64,
    pub runtime_artifact_reconciliation_samples: i64,
    pub runtime_archive_completion_samples: i64,
    pub artifact_attention_samples: i64,
    pub manifest_path_missing_samples: i64,
    pub archive_path_missing_samples: i64,
    pub collaboration_samples: i64,
    pub mix_minus_samples: i64,
    pub collaboration_transport_gap_samples: i64,
    pub packaging_ready_samples: i64,
    pub archive_complete_samples: i64,
    pub avg_bitrate_kbps: Option<f64>,
    pub peak_bitrate_kbps: Option<i64>,
    pub avg_viewers: Option<f64>,
    pub peak_viewers: Option<i64>,
    pub total_dropped_frames: i64,
    pub peak_collaboration_participants: i64,
    pub peak_active_output_routes: i64,
    pub peak_engine_node_count: i64,
    pub peak_engine_edge_count: i64,
    pub peak_mix_minus_edge_count: i64,
    pub peak_mirror_fanout_edge_count: i64,
    pub peak_bundle_attachment_count: i64,
    pub peak_bundle_mixer_count: i64,
    pub peak_bundle_fanout_count: i64,
    pub peak_bundle_return_count: i64,
    pub peak_media_stage_count: i64,
    pub peak_media_output_target_count: i64,
    pub peak_media_return_target_count: i64,
    pub peak_media_input_participant_count: i64,
    pub peak_media_mix_minus_participant_count: i64,
    pub peak_runtime_target_count: i64,
    pub peak_playback_target_count: i64,
    pub peak_recording_target_count: i64,
    pub peak_variant_target_count: i64,
    pub peak_collaboration_target_count: i64,
    pub peak_program_target_count: i64,
    pub peak_audio_target_count: i64,
    pub peak_engine_target_count: i64,
    pub peak_host_channel_count: i64,
    pub peak_mirror_channel_count: i64,
    pub peak_shared_program_mirror_channel_count: i64,
    pub peak_guest_isolated_mirror_channel_count: i64,
    pub peak_archive_target_count: i64,
    pub peak_active_target_count: i64,
    pub peak_degraded_target_count: i64,
    pub peak_armed_target_count: i64,
    pub peak_pending_source_target_count: i64,
    pub ll_hls_samples: i64,
    pub peak_discontinuity_sequence: i64,
    pub last_collected_at: Option<String>,
    pub last_runtime_state: Option<String>,
    pub last_packaging_status: Option<String>,
    pub last_archive_status: Option<String>,
    pub last_contribution_state: Option<String>,
    pub last_ingest_latency_ms: Option<i64>,
    pub last_source_probe_present: bool,
    pub last_source_validation_state: Option<String>,
    pub last_advisory_status: Option<String>,
    pub last_manifest_artifact_state: Option<String>,
    pub last_archive_artifact_state: Option<String>,
    pub last_collaboration_session_id: Option<String>,
    pub last_collaboration_participant_count: Option<i64>,
    pub last_collaboration_transport_gap_present: bool,
    pub last_active_output_routes: Option<i64>,
    pub last_audio_mix_mode: Option<String>,
    pub last_engine_node_count: Option<i64>,
    pub last_engine_edge_count: Option<i64>,
    pub last_mix_minus_edge_count: Option<i64>,
    pub last_mirror_fanout_edge_count: Option<i64>,
    pub last_bundle_attachment_count: Option<i64>,
    pub last_bundle_mixer_count: Option<i64>,
    pub last_bundle_fanout_count: Option<i64>,
    pub last_bundle_return_count: Option<i64>,
    pub last_media_stage_count: Option<i64>,
    pub last_media_output_target_count: Option<i64>,
    pub last_media_return_target_count: Option<i64>,
    pub last_media_input_participant_count: Option<i64>,
    pub last_media_mix_minus_participant_count: Option<i64>,
    pub last_runtime_target_count: Option<i64>,
    pub last_playback_target_count: Option<i64>,
    pub last_recording_target_count: Option<i64>,
    pub last_variant_target_count: Option<i64>,
    pub last_collaboration_target_count: Option<i64>,
    pub last_program_target_count: Option<i64>,
    pub last_audio_target_count: Option<i64>,
    pub last_engine_target_count: Option<i64>,
    pub last_host_channel_count: Option<i64>,
    pub last_mirror_channel_count: Option<i64>,
    pub last_shared_program_mirror_channel_count: Option<i64>,
    pub last_guest_isolated_mirror_channel_count: Option<i64>,
    pub last_archive_target_count: Option<i64>,
    pub last_active_target_count: Option<i64>,
    pub last_degraded_target_count: Option<i64>,
    pub last_armed_target_count: Option<i64>,
    pub last_pending_source_target_count: Option<i64>,
    pub last_runtime_class: Option<String>,
    pub last_latency_profile: Option<String>,
    pub last_ladder_policy: Option<String>,
    pub last_content_class: Option<String>,
    pub last_failure_at: Option<String>,
    pub last_failure_state: Option<String>,
    pub last_error: Option<String>,
}
